'use strict'

module.exports = [
  'accept',
  'accept-charset',
  'accept-encoding',
  'accept-datetime',
  'accept-language',
  'authorization',
  'cache-control',
  'connection',
  'cookie',
  'content-length',
  'content-type',
  'date',
  'expect',
  'forwarded',
  'from',
  'host',
  'if-match',
  'if-modified-since',
  'if-none-match',
  'if-range',
  'if-unmodified-since',
  'max-forwards',
  'origin',
  'pragma',
  'proxy-authorization',
  'range',
  'referer',
  'te',
  'user-agent',
  'upgrade',
  'via',
  'warning'
]
